config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :users do 
  	resources :companies, only: [:new, :create,  :edit, :update, :show] do
  		resources :parts
  	end
  end
get 'companies', to: 'companies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :parts
 	validates :name, presence: true, length: {minimum: 5, maximum: 15}
 	validates :description, presence: true, length: {minimum: 5, maximum: 30}
end

app/models/part.rb
class Part < ApplicationRecord
	belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :companies
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
  current_user
  end
  
  def not_found
  raise ActionController::RoutingError.new('Not Found')
  end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :authenticate_user!, :except => [:index, :show]
	def index
		@companies = Company.all.order('created_at DESC ')
	end

	def new
		@user = User.find_by(params[:id])
		@company = Company.new

	end

	def show
		@user = User.find(params[:user_id])
		@company = Company.find(params[:id])

	end



def create
	@company = current_user.companies.new(company_params)
	if @company.save
		flash[:success] = "Company has been saved"
		redirect_to user_path current_user

	else
		flash[:danger] = "Cant be saved"
		render 'new'
end

end

	def edit

	end

	def update

	end

	def destroy

	end

private

	def company_params
		params.require(:company).permit(:name, :description, :city_field, :state_field, :country_field, :expiration_date, :phone, :user_id)
	end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
before_action :authenticate_user!
def index

end


def show 
@part = Part.find(params[:id])
end


def new
	@user = User.find(params[:user_id])
	@company = @user.companies.find(params[:company_id])
	@part = Part.new

end

def create
	@company = Company.find(params[:company_id])
	@part = @company.parts.new(parts_params)
	@part.user_id = current_user.id
	if @part.save
		flash[:success] = "have been saved"
		redirect_to current_user
	else
		flash[:danger] = "not saved"
		render 'new'
	end

end


def edit

end


def update

end

def destroy

end

private

def parts_params
	params.require(:part).permit(:name, :description, :user_id, :company_id )

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
def index

end

def show
	@user = User.find(params[:id])
	@company = @user.companies.find_by(params[:company_id])
	@companies = current_user.companies.all.order('created_at DESC') if current_user

end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index 

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
		<%= simple_form_for [@user, @company] do |f| %>
			<div class="form-group">
			<%= f.label :name %>
			 <%= f.text_field :name,  class: "form-control stack", value: raw("&#xf007;"), style: "font-family: 'FontAwesome';"  %>
			</div>
			<div class="form-group">
			<%= f.label :description  %>
			<%= f.text_field :description,  class: "form-control stack", placeholder: raw("&#xf16c;"), style: "font-family: 'FontAwesome';" %>
			</div>
			
			<div class="form-group">
			<%= f.label :phone %>
			<%= f.text_field number_to_phone(:phone, pattern: /(\d{1,4})(\d{4})(\d{4})$/, area_code: true),  class: "form-control stack", placeholder: raw("&#xf16c;"), style: "font-family: 'FontAwesome';" %>
			</div>
			<div class="form-group">
			<%= f.label :expiration_date %>
			<%= f.text_field :expiration_date, data:{ provide:'datepicker' },  class: "form-control stack", placeholder: raw("&#xf16c;"), style: "font-family: 'FontAwesome';" %>
			</div>
			<div class="form-group">
			<%= f.input :country_field, label: "Country", collection: CountryStateSelect.countries_collection %>
			</div>
			<div class="form-group">
			<%= f.input :state_field, CountryStateSelect.state_options(label: "State / Province", form: f, field_names: { :country => :country_field, :state => :state_field } ) %>
			</div>
			<div class="form-group">
			<%= f.input :city_field, CountryStateSelect.city_options(label: "City ", form: f, field_names: {  :state => :state_field, :city => :city_field } ) %>
			</div>
		<%= f.submit class: "btn btn-primary" %>
		<% end %>

app/views/companies/index.html.erb
<% @companies.each do |company| %>
<p><%= company.name %> </p> 
<p><%= company.user.name %> </p> 
<% end %>

app/views/companies/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1 align="center">Tu Compania</h1>
	</div>
<%= render 'form' %>
</div>

app/views/companies/show.html.erb
<div class="container">
	<div class="row">
		

	</div>
</div>
<p><%= @company.name %></p>

<p><%= @company.description %></p>

<%= link_to "New Part", new_user_company_part_path(@user, @company, @part) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "AutoChile" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AutoChile</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to "HOME", root_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'EDIT PROFILE',edit_user_registration_path %></li>
            <li><%= link_to 'USER', user_path(current_user) %></li>
            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

            <% else %>          
            <li><%= link_to "SIGN UP", new_user_registration_path %></li>
            <li><%= link_to "LOG IN", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>



    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/parts/new.html.erb
<%= form_for [@user, @company, @company.parts.build] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>

	<%= f.text_field :description %>

<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Index all Users</h1>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-9">
		
<h1 align="center">Companias</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <% @companies.each do |company|%>
  <tbody>
    <tr>
      <th scope="row"><%=company.id %></th>
      <td><%=link_to company.name, user_company_path(@user, company)  %></td>
      <td><%= company.description %></td>
      <td>@mdo</td>
    </tr>
  </tbody>
  <% end  %>
</table>

	</div>
<% if user_signed_in? %>
        <div class="col-md-3">
          <div class="well sidebar-nav">
          <div align="center">
            <div  class="round-image-50 "><%= image_tag(current_user.avatar.url(:thumb)) %></div>

            </div>
            <p class="text-center"><%= current_user.name %></p>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Informacion de Usuario", edit_user_registration_path  %></li>
              <li><%= link_to "Agregar nueva compania", new_user_company_path(@company)  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <% end %>


</div>

app/views/welcome/index.html.erb
<h1>Home</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dictum gravida volutpat. Donec imperdiet erat vel purus tempor mattis. Phasellus tincidunt </p><p>sagittis lacus, sit amet convallis velit facilisis ac. Fusce vulputate dolor nec nisi tempus suscipit. Phasellus non luctus nunc, ac convallis diam. Quisque sodales</p><p>magna ac nisl suscipit, quis convallis erat suscipit. In venenatis diam nunc, id vehicula metus porta congue. Mauris ut consequat purus, id tincidunt ligula. Nunc eu turpis lorem. Nunc dignissim mi a turpis imperdiet sodales. Curabitur sem metus, facilisis sit amet posuere id, auctor sed velit.</p> 